apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-app
spec:
  containers:
  - name: web-server-apache
    image: httpd
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
spec:
  type: NodePort 
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: web-app