apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
  - name: redis-container
    image: redis
    #dentro do container
    volumeMounts:
    - mountPath: "/my-data"
      name: "my-hostpath-vol"

  volumes:
  - name: "my-hostpath-vol"
    hostPath:
      path: "/var/lib/2-persist"