apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-blue
  name: nginx-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    # Label para diferenciar
  template:
    metadata:
      labels:
        app: nginx
      # Adiciona o label version
    spec:
      containers:
      - name: ngnix
        image: ngnix
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-green
  name: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      # Label para diferenciar
  template:
    metadata:
      labels:
        app: nginx
        # Adiciona o label version
    spec:
      containers:
      - name: httpd
        image: httpd
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    app: nginx  # Mantém o label base
    # Adiciona um label específico para nginx-blue
  ports:
  - port: 80
  type: LoadBalancer
