apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    apps: app-java
spec:
  containers:
  - name: container-tomcat
    image: tomcat

  # kubectl exec -it tomcat-pod -- bash
  # apt update
  # apt install iputils-ping -y
  # pingar o ip do outro container
  # para descobrir o ip do outro container
  # -> kubectl describe pods redis-pod |grep IP
  # kubectl describe pods redis-pod |grep IP